[project]
name = "15-umap-gpu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.3.3",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
